version: '3.1'

services:
  db:
    container_name: quivr-postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: quivr
      POSTGRES_USER: quivr
      POSTGRES_PASSWORD: quivr

  adminer:
    container_name: quivr-adminer
    image: adminer
    restart: always
    ports:
      - 9090:8080

  postgrest:
    container_name: quivr-postgrest
    image: postgrest/postgrest:v11.1.0
    ports:
      - 4000:3000
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/quivr
      PGRST_DB_SCHEMAS: quivr
      PGRST_DB_ANON_ROLE: quivr_anon
      PGRST_LOG_LEVEL: info
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:4000
    depends_on:
      - db
  
  postgrest-swagger:
    container_name: quivr-postgrest-swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      API_URL: http://localhost:4000/
